# Generated by Django 5.0.1 on 2024-01-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockTransaction',
            new_name='MouvementStock',
        ),
    ]
