# Generated by Django 5.0.1 on 2024-01-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_alter_produit_category_alter_produit_fournisseur_and_more'),
        ('stock', '0005_alter_mouvementstock_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produit.produit'),
        ),
    ]
